In [35]:
# libraries
import pandas as pd
import sqlite3

In [36]:
# This creates the database file if it doesn't exist
conn = sqlite3.connect("school.db")
cur = conn.cursor()

1.Creating students table

In [37]:
create_table_query = """
CREATE TABLE IF NOT EXISTS Students (
    StudentID INT PRIMARY KEY,
    Name VARCHAR(50),
    Age INT,
    City VARCHAR(50)
);
"""

cur.execute(create_table_query)
conn.commit()

In [38]:
# Check if table exists
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
tables

          name
0     Students
1      Courses
2  Enrollments

In [39]:
cur.execute("""SELECT name FROM sqlite_master WHERE type = 'table';""")
# Fetch the result and store it in table_names
table_names = cur.fetchall()
table_names

[('Students',), ('Courses',), ('Enrollments',)]

1.2 Inserting data to student table

In [40]:
cur.execute("""
INSERT INTO Students (StudentID, Name, Age, City) VALUES
(1, 'Wanjiru', 20, 'Nairobi'),
(2, 'Kamau', 22, 'Mombasa'),
(3, 'Achieng', 21, 'Kisumu'),
(4, 'Otieno', 23, 'Nakuru'),
(5, 'Mwende', 19, 'Eldoret'),
(6, 'Nandwa', 24, 'Marigat'),
(7, 'Halima', 27, 'Voi');
""")
conn.commit()

IntegrityError: UNIQUE constraint failed: Students.StudentID

2.Creating Courses table

In [ ]:
create_table_query = """ 
CREATE TABLE IF NOT EXISTS Courses (
    CourseID INT PRIMARY KEY,
    CourseName VARCHAR(100),
    Credits INT
);
"""
cur.execute(create_table_query)
conn.commit()

2.2 Inserting data to courses table

In [ ]:
cur.execute("""
INSERT INTO Courses (CourseID, CourseName, Credits) VALUES
(101, 'SQL Basics', 3),
(102, 'Data Analysis', 4),
(103, 'Web Development', 5),
(104, 'Machine Learning', 4),
(105, 'Deep Learning', 5);
""")
conn.commit()

3. Creating Enrollment table

In [ ]:
create_table_query = """ 
CREATE TABLE Enrollments (
    EnrollmentID INT PRIMARY KEY,
    StudentID INT,
    CourseID INT,
    EnrollmentDate DATE,
    FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID)
);
"""
cur.execute(create_table_query)
conn.commit()

3.2 Inserting data to enrollment table

In [ ]:
cur.execute("""
INSERT INTO Enrollments (EnrollmentID, StudentID, CourseID, EnrollmentDate) VALUES
(1, 1, 101, '2023-01-15'),
(2, 1, 102, '2023-01-16'),
(3, 2, 101, '2023-01-17'),
(4, 3, 103, '2023-01-18'),
(5, 4, 104, '2023-01-19'),
(6, 5, 102, '2023-01-20'),
(7, Null, 105,'2023-01-21');
""")
conn.commit()

In [ ]:
#View data
query= """SELECT * FROM Students""" 
pd.read_sql(query, conn)

   StudentID     Name  Age     City
0          1  Wanjiru   20  Nairobi
1          2    Kamau   22  Mombasa
2          3  Achieng   21   Kisumu
3          4   Otieno   23   Nakuru
4          5   Mwende   19  Eldoret
5          6   Nandwa   24  Marigat
6          7   Halima   27      Voi

In [ ]:
#View data
query= """SELECT * FROM Courses""" 
pd.read_sql(query, conn)

   CourseID        CourseName  Credits
0       101        SQL Basics        3
1       102     Data Analysis        4
2       103   Web Development        5
3       104  Machine Learning        4
4       105     Deep Learning        5

In [ ]:
#View data
query= """SELECT * FROM Enrollments""" 
pd.read_sql(query, conn)

   EnrollmentID  StudentID  CourseID EnrollmentDate
0             1        1.0       101     2023-01-15
1             2        1.0       102     2023-01-16
2             3        2.0       101     2023-01-17
3             4        3.0       103     2023-01-18
4             5        4.0       104     2023-01-19
5             6        5.0       102     2023-01-20
6             7        NaN       105     2023-01-21

In [ ]:
#Inner Join
q=""" 
  SELECT * 
  FROM Students s
  INNER JOIN Enrollments e
  ON s.StudentID = e.StudentID;
  """ 
pd.read_sql(q, conn)

,StudentID,Name,Age,City,EnrollmentID,StudentID,CourseID,EnrollmentDate
0,1,Wanjiru,20,Nairobi,1,1,101,2023-01-15
1,1,Wanjiru,20,Nairobi,2,1,102,2023-01-16
2,2,Kamau,22,Mombasa,3,2,101,2023-01-17
3,3,Achieng,21,Kisumu,4,3,103,2023-01-18
4,4,Otieno,23,Nakuru,5,4,104,2023-01-19
5,5,Mwende,19,Eldoret,6,5,102,2023-01-20

In [ ]:
#Selecting specific columns from the INNER JOIN
q=""" 
  SELECT s.StudentID,s.Name,e.EnrollmentID,e.CourseID
  FROM Students s
  INNER JOIN Enrollments e
  ON s.StudentID = e.StudentID;
  """ 
pd.read_sql(q, conn)

   StudentID     Name  EnrollmentID  CourseID
0          1  Wanjiru             1       101
1          1  Wanjiru             2       102
2          2    Kamau             3       101
3          3  Achieng             4       103
4          4   Otieno             5       104
5          5   Mwende             6       102

In [ ]:
#Left Join
q=""" 
  SELECT * 
  FROM Students s
  LEFT JOIN Enrollments e
  ON s.StudentID = e.StudentID;

"""
pd.read_sql(q, conn)

,StudentID,Name,Age,City,EnrollmentID,StudentID,CourseID,EnrollmentDate
0,1,Wanjiru,20,Nairobi,1.0,1.0,101.0,2023-01-15
1,1,Wanjiru,20,Nairobi,2.0,1.0,102.0,2023-01-16
2,2,Kamau,22,Mombasa,3.0,2.0,101.0,2023-01-17
3,3,Achieng,21,Kisumu,4.0,3.0,103.0,2023-01-18
4,4,Otieno,23,Nakuru,5.0,4.0,104.0,2023-01-19
5,5,Mwende,19,Eldoret,6.0,5.0,102.0,2023-01-20
6,6,Nandwa,24,Marigat,NaN,NaN,NaN,None
7,7,Halima,27,Voi,NaN,NaN,NaN,None

In [ ]:
#Right Join-Left
q=""" 
  SELECT * 
  FROM Enrollments e
  LEFT JOIN Students s
  ON s.StudentID = e.StudentID;

"""
pd.read_sql(q, conn)

,EnrollmentID,StudentID,CourseID,EnrollmentDate,StudentID,Name,Age,City
0,1,1.0,101,2023-01-15,1.0,Wanjiru,20.0,Nairobi
1,2,1.0,102,2023-01-16,1.0,Wanjiru,20.0,Nairobi
2,3,2.0,101,2023-01-17,2.0,Kamau,22.0,Mombasa
3,4,3.0,103,2023-01-18,3.0,Achieng,21.0,Kisumu
4,5,4.0,104,2023-01-19,4.0,Otieno,23.0,Nakuru
5,6,5.0,102,2023-01-20,5.0,Mwende,19.0,Eldoret
6,7,NaN,105,2023-01-21,NaN,None,NaN,None

In [ ]:
#Inner Join of the three tables
q =""" 
SELECT s.Name, c.CourseName 
FROM Students s 
INNER JOIN Enrollments e
ON s.StudentID = e.StudentID
INNER JOIN Courses c
ON e.CourseID = c.CourseID

"""
pd.read_sql(q, conn)

      Name        CourseName
0  Wanjiru        SQL Basics
1  Wanjiru     Data Analysis
2    Kamau        SQL Basics
3  Achieng   Web Development
4   Otieno  Machine Learning
5   Mwende     Data Analysis

In [ ]:
#Full outer Join students table and enrollments table
#Using UNION ALL
q = """  
SELECT s.StudentID, s.Name, e.CourseID
FROM Students s
LEFT JOIN Enrollments e
ON s.StudentID = e.StudentID
UNION  
SELECT s.StudentID, s.Name, e.CourseID
FROM Enrollments e
LEFT JOIN Students s
ON e.StudentID = s.StudentID;
"""
pd.read_sql(q, conn)

   StudentID     Name  CourseID
0        NaN     None     105.0
1        1.0  Wanjiru     101.0
2        1.0  Wanjiru     102.0
3        2.0    Kamau     101.0
4        3.0  Achieng     103.0
5        4.0   Otieno     104.0
6        5.0   Mwende     102.0
7        6.0   Nandwa       NaN
8        7.0   Halima       NaN

In [ ]:
# Steve's Code
#Need to update learn env
q = '''
         SELECT *
         FROM Students s
         LEFT JOIN Enrollments e 
         ON s.StudentID = e.StudentID
         UNION ALL
         SELECT *
         FROM Students s
         RIGHT JOIN Enrollments e 
         ON s.StudentID = e.StudentID;
    '''

SUBQUERIES

In [ ]:
#SUBQUERIES INSIDE A QUERY
q= '''
   SELECT s.Name,
           (SELECT COUNT(*)
           FROM Enrollments e
           WHERE e.StudentID = s.StudentID)AS TotalCourses
           FROM Students s;
    '''

In [ ]:
pd.read_sql(q,conn)

      Name  TotalCourses
0  Wanjiru             2
1    Kamau             1
2  Achieng             1
3   Otieno             1
4   Mwende             1
5   Nandwa             0
6   Halima             0

In [ ]:
#subquery in the From statement
#Subquery in the FROM Statement

q = '''
        SELECT Name, TotalCourses
        FROM (
                SELECT s.Name, COUNT(e.CourseID) AS TotalCourses
                FROM Students s 
                LEFT JOIN Enrollments e
                ON s.StudentID = e.StudentID
                GROUP BY s.Name
                )
        ORDER BY TotalCourses DESC;
    
     ''' 
pd.read_sql(q, conn)

      Name  TotalCourses
0  Wanjiru             2
1  Achieng             1
2    Kamau             1
3   Mwende             1
4   Otieno             1
5   Halima             0
6   Nandwa             0

In [ ]:
# subquery in the where statement
q = '''
        SELECT Name
        FROM Students
        WHERE StudentID IN (
                             SELECT StudentID
                             FROM Enrollments
                             WHERE CourseID >= 101)
    ;
     ''' 
pd.read_sql(q, conn)

      Name
0  Wanjiru
1    Kamau
2  Achieng
3   Otieno
4   Mwende

In [43]:
#finding students enrolled in Data analysis
q ='''
   SELECT Name
   FROM Students s
   INNER JOIN Enrollments e
     ON s.StudentID = e.StudentId
   INNER JOIN Courses c
     ON e.CourseID = c.CourseID
   WHERE c.CourseName="Data Analysis"
   ;
   '''
pd.read_sql(q, conn)

      Name
0  Wanjiru
1   Mwende

In [42]:
q = '''
SELECT s.Name
FROM Students s
INNER JOIN Enrollments e
    ON s.StudentID = e.StudentID
INNER JOIN Courses c
    ON e.CourseID = c.CourseID
WHERE c.CourseName = "Data Analysis"
'''
pd.read_sql(q, conn)

      Name
0  Wanjiru
1   Mwende

In [44]:
q = '''
SELECT Name
FROM Students
WHERE StudentID IN (
    SELECT StudentID
    FROM Enrollments
    WHERE CourseID = (
        SELECT CourseID
        FROM Courses
        WHERE CourseName = "Data Analysis"
    )
)
'''
pd.read_sql(q, conn)

      Name
0  Wanjiru
1   Mwende

In [46]:
#view is a virtual Table
#it can be defined as a saved sql query stored in a database
conn.execute('''
CREATE VIEW studentcourseview As 
SELECT s.Name,c.CourseName,e.Enrollment
FROM Students s
INNER JOIN Enrollments e ON s.StudentID = e.StudentID
INNER JOIN Courses c ON e.CourseID = c.CourseID
''')

In [47]:
pd.read_sql(''' SELECT* FROM studentcourseview;''',conn)

DatabaseError: Execution failed on sql ' SELECT* FROM studentcourseview;': no such column: e.Enrollment

In [48]:
conn.execute('''
CREATE VIEW studentcourseview AS
SELECT s.Name,
       c.CourseName
FROM Students s
INNER JOIN Enrollments e
    ON s.StudentID = e.StudentID
INNER JOIN Courses c
    ON e.CourseID = c.CourseID
''')

In [49]:
pd.read_sql("SELECT * FROM studentcourseview;", conn)

      Name        CourseName
0  Wanjiru        SQL Basics
1  Wanjiru     Data Analysis
2    Kamau        SQL Basics
3  Achieng   Web Development
4   Otieno  Machine Learning
5   Mwende     Data Analysis